services:
  guestbook:
    build: .
    image: guestbook:v0.1.0
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  jupyter:
    image: quay.io/jupyter/datascience-notebook:python-3.12
    ports:
      - "8888:8888"
    volumes:
      - jupyter_notebooks:/home/jovyan/work
      - jupyter_data:/home/jovyan/.local
      - ./datasets:/home/jovyan/datasets
      - ./examples:/home/jovyan/work/examples
    user: root
    environment:
      - JUPYTER_TOKEN=monmotdepasse
      - CHOWN_EXTRA=/home/jovyan/.local
      - CHOWN_EXTRA_OPTS=-R

volumes:
  redis_data:
  jupyter_notebooks:
  jupyter_data:
